test: messaging,ctypes,contacts module tests and fixes 721,718
KILTprotocol/prototype-services pull request #75
Opened 2020-08-28 12:54 UTC by LeonFLK

## fixes KILTProtocol/ticket#312, KILTprotocol/ticket#721,  KILTprotocol/ticket#718

- [x] CTypes module
- [ ] Messaging Module
- [ ] Contacts Module
- [ ] Faucet Module
- [ ] Blockchain Module, config service ???

This introduces unit testing of controller and service for each core module.
Removes naive approach of in-memory unit testing.
Also aims to refactor some minor issues within our classes.
Please give feedback whether we should or should not test non-core modules.

## Checklist:

- [ ] I have verified that the code works
- [ ] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [ ] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

2020-09-02 16:34 UTC, rflechtner requested changes
Be sure to `await` any `expect(async() => {}).resolves` and `expect(async() => {}).rejects` like this: 
`await expect(async() => true).resolves.toBeTruthy()`
Other than that I have no functional complaints, the remaining comments are all style-related. To summarise, there's two things that could help readability of the tests:
1. Choose one way to mock async functions and to return promises. My personal favourite is `async(): Promise<any> => value`, i.e. `async(): Promise<void> => {}`. `(): Promise<any> => Promise.resolve(value)` also works, but `async (): Promise<any> => Promise.resolve(value)` seems a bit redundant
2. Separate negative and positive tests. In general its nicer not to lump too many different cases in one `it()`, but checking happy path & correct error handling should definitely be two tests imo

2020-09-02 16:43 UTC, LeonFLK commented on src/ctypes/ctypes.module.spec.ts
> +      .mockReturnValue({ exec: () => Optional.ofNullable(null) })
yes

2020-09-02 16:45 UTC, LeonFLK commented on src/contacts/contacts.module.spec.ts
> +        )
Yeah for mopst tests I like to have them purely separated, but for this one it jest depends on one missing property, so I think these negative tests are all somehow related, as they trigger the same response from the controller.

2020-09-02 16:45 UTC, LeonFLK commented on src/contacts/contacts.module.spec.ts
> +        expect(addSpy).toHaveBeenCalledTimes(0)
Yes, explicitly stating that the function should not have been called is great!

2020-09-04 08:47 UTC, rflechtner commented on src/contacts/contacts.module.spec.ts
> +        )
true, but that's a reason to group the negative tests, not one to lump them together with the positive test. What I meant was move them out of this test, like so: 
```typescript
      it('calls contactService.add on valid Contact without Did', async () => {
        const addSpy = jest.spyOn(contactsService, 'add')
        expect(await contactsController.add(testContact)).toEqual(undefined)
        expect(mockedHashStr).not.toHaveBeenCalled()
        expect(mockedVerify).not.toHaveBeenCalled()
        expect(addSpy).toHaveBeenCalledTimes(1)
        expect(addSpy).toHaveBeenCalledWith(testContact)
        addSpy.mockClear()
      })
      it('rejects contact if property missing', async () => {
        const addSpy = jest.spyOn(contactsService, 'add')
        const noAddressContact: Contact = {
          ...testContact,
          publicIdentity: { ...testContact.publicIdentity, address: '' },
        }
        const noPubKeyContact: Contact = {
          ...testContact,
          publicIdentity: {
            ...testContact.publicIdentity,
            boxPublicKeyAsHex: '',
          },
        }
        const noNameContact: Contact = {
          ...testContact,
          metaData: {
            ...testContact.metaData,
            name: '',
          },
        }
        await expect(contactsController.add(noAddressContact)).rejects.toThrow(
          BadRequestException
        )
        await expect(contactsController.add(noPubKeyContact)).rejects.toThrow(
          BadRequestException
        )
        await expect(contactsController.add(noNameContact)).rejects.toThrow(
          BadRequestException
        )
        expect(mockedHashStr).not.toHaveBeenCalled()
        expect(mockedVerify).not.toHaveBeenCalled()
        expect(addSpy).not.toHaveBeenCalled()
      })
```

2020-09-04 08:49 UTC, rflechtner commented on src/contacts/contacts.module.spec.ts
> +        )
btw you may be able to replace all those `spy.mockClear()` with a call in `beforeAll` to [clear/reset all mocks](https://jestjs.io/docs/en/jest-object#jestclearallmocks)

2020-09-04 09:11 UTC, rflechtner requested changes
the failing integration tests indicate that this broke the API by requiring that a KILT address be sent to the faucet endpoint. You basically have two options to fix this:
1. translate a public key to an address before running it through the address validator. In this case it would be cool to amend integration tests so that we call the faucet endpoint with both an address and a public key. Just add an extra test for address.
2. change the api. This would of course require changing the integration tests, but most importantly we'd have to change the `pubkey` key in the payload to `address`; imho we can't ask for a public key but secretly require an address, even in a non-public api. This would mean changing the faucet implementation as well.

2020-09-04 11:18 UTC, LeonFLK commented on src/contacts/contacts.module.spec.ts
> +        )
Ohh yes of course, I missed that I had really the one positive in there as well. This should be split!
I would expand the use of an afterEach to call clearAllMocks().

2020-09-04 11:26 UTC, LeonFLK commented
Good points, and yes you are requesting with a pubkey in the Integration tests. I'll talk to TImo, what the services should be capable of. But I think the best solution atm for this would be to convert to address before checking validity and eligibility.

2020-09-04 13:11 UTC, LeonFLK commented
Wir wollen nur die addresse erwarten und akzeptieren.

2020-09-04 15:06 UTC, rflechtner approved these changes
Nice! There's an error message to fix (see my comment) but then you're good to go!

2020-09-04 15:13 UTC, LeonFLK commented on src/faucet/faucet.controller.ts
>        throw new BadRequestException('no public key')
target address sounds good, will push then merge

2020-09-04 15:36 UTC, merged