Have basic Authorization for retrieval and deletion of messages
KILTprotocol/prototype-services pull request #78
Opened 2020-09-04 15:34 UTC by LeonFLK

## fixes KILTProtocol/ticket#719

Adds basic header authorization to the message module, to restrict read access to only the receiver and the sender as well as restrict message deletion to receiver of the message.

If you want to fetch the received messaged for a specific identity, supply the with the identity signed address inside the header as signature key.
If you want to fetch the sent messaged for a specific identity, supply the with the identity signed address inside the header as signature key.
If you want to delete a specific message with the messageId, supply the with the receiver identity signed messageId inside headers as signature key.

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [x] I have documented the changes (where applicable)

2020-09-04 17:10 UTC, rflechtner reviewed
I like the idea of restricting messages to the in / outbox; however the authentication scheme of signing your address is trivial to circumvent and could encourage bad practice in the worst case. Because we sign the same string every time, anyone intercepting a successful request could again request all of this addresses incoming and outgoing messages. If we're serious about this, we'd need to answer a challenge sent by the server as they do in the [HOBA scheme](https://tools.ietf.org/html/rfc7486#section-3) or [SCRAM](https://tools.ietf.org/html/rfc7804). Of course this would be quite a bit more work... maybe there is already a next.js implementation for that out there? BTW are we following HTTP authentication specs here or are we being creative? (I'd love to see some integration tests to understand what a request for this would look like).
The scheme may be more secure when signing a unique message id for deletion, which is a one-off operation. Re the implementation, I'd propose you add a `findById` method to the message service, then handle the authentication stuff on the controller - my intuition tells me that's where those kinds of things belong.

2020-09-04 17:35 UTC, rflechtner commented
Signing a date header with the current time as proposed [here](https://medium.com/@technospace/ensuring-message-integrity-with-http-signatures-86f121ac9823) may be a low-effort solution that is a bit more secure?

2020-09-09 14:03 UTC, LeonFLK commented
We don't care about inbox and outbox, we only care about authorizing the delete of a message.
For now we are going to stick to this approach, and are going to change this when we adopt DIDcomm or other means of authorization and security.

2020-09-10 11:22 UTC, rflechtner requested changes
LGTM, just throw out the `yarn.lock` changes pls! And maybe have another look at the error string with which we respond to unresolvable signatures.

2020-09-10 11:22 UTC, rflechtner commented on src/messaging/messaging.controller.ts
> +    }).receiverAddress
I <3 destructuring
```suggestion
    const {receiverAddress} = (await this.messagingService.findById(
      id
    )).orElseThrow(() => {
      throw new ForbiddenMessageAccessException()
    })
```

2020-09-10 11:22 UTC, rflechtner commented on test/messaging.e2e-spec.ts
> +    // should this give 400 or 403, or rather do we want to provide information if the id is unregistered?
probably 403 bc we don't want to reveal the info that this id exists - but I'm undecided as ids are not protected anyway as of now (you can read them knowing someone's address)

2020-09-10 11:22 UTC, rflechtner commented on yarn.lock
>  kind-of@^6.0.0, kind-of@^6.0.2:
I imagine this is a rebase artifact? don't see a reason why we would downgrade

2020-09-15 09:33 UTC, LeonFLK commented on src/ctypes/ctypes.module.spec.ts
> +      .mockReturnValue({ exec: async (): Promise<CTypeDB> => null })
Oh yes, when I implemented the findById for the message service, which uses the models findOne, I noticed that I had set the wrong return types.
findOne does not return an optional (duhh...), but just resolves null when it finds nothing.

2020-09-15 09:38 UTC, LeonFLK commented on src/messaging/messaging.controller.ts
> +    }).receiverAddress
Yes you do

2020-09-15 09:41 UTC, LeonFLK commented on yarn.lock
>  kind-of@^6.0.0, kind-of@^6.0.2:
Me neither

2020-09-15 09:42 UTC, LeonFLK commented on yarn.lock
>  kind-of@^6.0.0, kind-of@^6.0.2:
maybe because I didn't base this branch on develop initially

2020-09-15 10:29 UTC, LeonFLK commented on src/messaging/exceptions/message-forbidden.exception.ts
> +    super('Invalid address given', HttpStatus.FORBIDDEN)
Yeah I agree

2020-09-15 12:26 UTC, merged