Update stored contacts with deprecated DID Format, respond with SDK Format for outdated Contacts
KILTprotocol/prototype-services pull request #87
Opened 2020-11-18 20:03 UTC by LeonFLK

## fixes KILTProtocol/ticket#744
When Contact with deprecated format exists in DB we delete on update and respond SDK format.

## How to test:
docker-compose up -d mongodb
start old democlient and old services
register Contact with DID in deprecated format
restart services with this PR included
visit http://localhost:3000/contacts
contact DID should be displayed in updated sdk format

## Checklist:

- [x] I have verified that the code works
- [x] I have verified that the code is easy to understand
  - [ ] If not, I have left a well-balanced amount of inline comments
- [x] I have [left the code in a better state](https://deviq.com/boy-scout-rule/)
- [ ] I have documented the changes (where applicable)

2020-11-19 09:30 UTC, rflechtner commented
I'm not sure I get what is going on here. We display the outdated DID format in the new format? I think I remember that the problem was that the old signature is just not valid over the new format. Have we solved this somehow?

2020-11-20 12:54 UTC, LeonFLK commented
Hey @rflechtner, sorry that I didn't clarify, though I did mentioned it to you, the old signature IS valid even for the  new format, as the signature is built with the same data

2020-11-20 14:54 UTC, rflechtner commented
> Hey @rflechtner, sorry that I didn't clarify, though I remember mentioning it to you, the old signature IS valid even for the new format, as the signature is essentially built the same way with the same data and they match .

Yeah sorry man I can't seem to remember. So when I run the resulting object through the sdk or the did resolver, they would validate the signature correctly, regardless of whether it was originally part of the old or the new format?

2020-11-20 14:56 UTC, LeonFLK commented
No worries, might have been some time ago :roll_eyes: ...the resulting signatures match!

2020-11-27 13:08 UTC, rflechtner requested changes
Seems to do what it is supposed to do 👍 
I had a hard time reviewing because it was not easy to understand what the original format looked like and what we'd have to do to translate. In-line comments and appropriate typing could help!

2020-11-27 13:08 UTC, rflechtner commented on src/contacts/mongodb-contacts.service.ts
> +      did: actualDid,
I guess 
```suggestion
      did: contactDB.signature && did ? {...did, signature: contactDB.signature} : did,
```
would also do it?

2020-11-27 13:08 UTC, rflechtner commented on src/contacts/mongodb-contacts.service.ts
> +      did: actualDid,
in fact when you add the optional `{signature?: string}` to the signature you could even make this more concise by adding `signature` to 
```
const { metaData, did, publicIdentity } = contactDB
```

2020-11-27 13:08 UTC, rflechtner commented on src/contacts/mongodb-contacts.service.ts
> +        })
can you add a comment describing why we need to delete the existing entry first?

2020-11-27 13:08 UTC, rflechtner commented on src/contacts/mongodb-contacts.service.ts
> +        })
I.e. why an update just won't do the trick?

2020-11-27 13:33 UTC, LeonFLK commented on src/contacts/mongodb-contacts.service.ts
> +        })
Yes, sure, also for here: ran into issues with updating as this keeps the old properties as artifacts or something, it does not exactly replace the stored document, removing the signature outer property.

2020-11-27 13:45 UTC, LeonFLK commented on src/contacts/mongodb-contacts.service.ts
>    private convertToContact(contactDB: ContactDB): Contact {
Yeah, I really wasn't sure how to deal with "shadow" properties, but i seems like this is a great way to deal with potential shadow properties

2020-11-27 20:36 UTC, merged